export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
export const ADD_FRIEND_FAIL = 'ADD_FRIEND_FAIL';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';

export const GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST';
export const GET_FRIEND_FAIL = 'GET_FRIEND_FAIL';
export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS';

export const GET_SINGLE_FRIEND_REQUEST = 'GET_SINGLE_FRIEND_REQUEST';
export const GET_SINGLE_FRIEND_FAIL = 'GET_SINGLE_FRIEND_FAIL';
export const GET_SINGLE_FRIEND_SUCCESS = 'GET_SINGLE_FRIEND_SUCCESS';
